//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Menu
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassMenu
    {
        public int ID { get; set; }
        public int ClassId { get; set; }
        public int IdDish { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Dish Dish { get; set; }

        public override string ToString()
        {
            return Date.ToString("d");
        }
    }
}
