//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Menu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Norm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Norm()
        {
            this.Classes = new HashSet<Class>();
        }
    
        public int NormId { get; set; }
        public int DaylyRate { get; set; }
        public double NormCarbohydrates { get; set; }
        public double NormFats { get; set; }
        public double NormProteins { get; set; }
        public double Break { get; set; }
        public double Din { get; set; }
        public double Aft { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Class> Classes { get; set; }
    }
}
